hub:
  db:
    type: sqlite-memory

proxy:
  service:
    type: NodePort
    nodePorts:
      http: 32372

cull:
  enabled: false


singleuser:
  startTimeout: 1200

  storage:
    type: none

  extraEnv:
    HOME: /home/iccbs
    NB_USER: iccbs

  image:
    name: quay.io/jupyter/pytorch-notebook
    tag: cuda12-latest
    pullPolicy: Always

  #storage:
    #type: dynamic
    #homeMountPath: /home/iccbs
    #capacity: 450Gi
    #dynamic:
    # pvcNameTemplate: claim-{username}
     #storageClass: nfs-shared

    #extraVolumes:
     #- name: shared-datasets
       #persistentVolumeClaim:
         #claimName: jupyterhub-shared-data

    #extraVolumeMounts:
     #- name: shared-datasets
       #mountPath: /home/iccbs/shared-datasets

  profileList:

    - display_name: "ICCBS CP2K Quantum Chemistry"
      description: "GPU-accelerated environment for quantum chemistry, DFT, and MD simulations using CP2K"
      kubespawner_override:
        image: registry-1.docker.io/ahsonlatif/ai-cp2k-chem:latest
        cpu_limit: 12            # allow up to 12 cores per user
        cpu_guarantee: 6         # guaranteed 6 cores
        mem_limit: 64G           # max 64 GiB RAM
        mem_guarantee: 32G       # guaranteed 32 GiB RAM
        extra_resource_limits:
          nvidia.com/gpu: "1"   # single shared GPU
        node_selector:
          kubernetes.io/hostname: ai-master
        fs_gid: 100
        uid: 1000


    - display_name: "ICCBS PyTorch Deep Learning"
      description: "GPU-enabled research environment for deep learning and AI workflows using PyTorch"
      kubespawner_override:
        image: registry-1.docker.io/ahsonlatif/pytorch_deeplearning:latest
        cpu_limit: 4
        cpu_guarantee: 2
        mem_limit: 32G
        mem_guarantee: 16G
        extra_resource_limits:
          nvidia.com/gpu: "1"
        # --- CRITICAL ADDITIONS BELOW ---
        environment:
          NVIDIA_VISIBLE_DEVICES: "all"
          NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
        # --------------------------------
        node_selector:
          kubernetes.io/hostname: node1
        uid: 1000   # Use 'uid' instead of 'run_as_uid' for KubeSpawner
        fs_gid: 100

    - display_name: "ICCBS GROMACS Molecular Dynamics"
      description: "GPU-accelerated environment"
      kubespawner_override:
        image: registry-1.docker.io/ahsonlatif/gromacs-jupyter:cuda12

        cpu_limit: 6
        cpu_guarantee: 3
        mem_limit: 24G
        mem_guarantee: 12G

        extra_resource_limits:
          nvidia.com/gpu: "1"

        node_selector:
          kubernetes.io/hostname: node1

    # 🔥 THIS disables NFS PVC
        #storage:
          #type: none

    # ✅ correct keys
        extraVolumes:
          - name: home
            hostPath:
              path: /data/jupyter-gromacs
              type: DirectoryOrCreate

        extraVolumeMounts:
          - name: home
            mountPath: /home/iccbs

        uid: 1000
        fs_gid: 100

    - display_name: "ICCBS Bioinformatics AI"
      description: "High-performance GPU-based environment"
      kubespawner_override:
        notebook_dir: /home/iccbs
        image: registry-1.docker.io/ahsonlatif/iccbs-bioinformatics:latest
        cpu_limit: 8
        cpu_guarantee: 4
        mem_limit: 32G
        mem_guarantee: 16G
        extra_resource_limits:
          nvidia.com/gpu: "1"
        node_selector:
          kubernetes.io/hostname: ai-38
         # 🔥 THIS disables NFS PVC
        #storage:
          #type: none
        extraVolumes:
          - name: home
            hostPath:
              path: /data/jupyter-bio
              type: DirectoryOrCreate

        extraVolumeMounts:
          - name: home
            mountPath: /home/iccbs

        uid: 1000
        fs_gid: 100

    - display_name: "ICCBS Bio & Chemical AI Research"
      description: "GPU-enabled environment for bioinformatics, cheminformatics, and AI-driven molecular research"
      kubespawner_override:
        image: registry-1.docker.io/ahsonlatif/ai_bio_chem:latest
        cpu_limit: 8
        cpu_guarantee: 4
        mem_limit: 32G
        mem_guarantee: 16G
        extra_resource_limits:
          nvidia.com/gpu: "1"
        node_selector:
          kubernetes.io/hostname: ai-master
        fs_gid: 100
        uid: 1000
