apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-shared-data-pv
spec:
  capacity:
    storage: 3Ti
  accessModes:
    - ReadWriteMany  # Crucial: allows all nodes to mount it at once
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-shared # We give it a custom name
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/shared-data
    server: 172.16.2.40 # AI-Master IP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyterhub-shared-data
  namespace: iccbs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-shared
  resources:
    requests:
      storage: 3Ti
