apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-iccbsai-2
  namespace: iccbs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 450Gi
  storageClassName: nfs-shared
  volumeName: pv-iccbsai-2
