apiVersion: v1
data:
  snmp.yml: |
    auths:
      cisco_v2:
        version: 2
        community: ICCBS-RO

    modules:
      cisco:

        walk:
          - 1.3.6.1.2.1.1
          - 1.3.6.1.2.1.2.2
          - 1.3.6.1.2.1.31.1.1
          - 1.3.6.1.4.1.9.9.109.1.1.1.1
          - 1.3.6.1.4.1.9.9.48.1.1.1
          - 1.3.6.1.4.1.9.9.13.1

        metrics:

          # ===== UPTIME =====
          - name: sysUpTime
            oid: 1.3.6.1.2.1.1.3.0
            type: gauge

          # ===== CPU =====
          - name: cpmCPUTotal5minRev
            oid: 1.3.6.1.4.1.9.9.109.1.1.1.1.8
            type: gauge
            indexes:
              - labelname: cpu
                type: gauge

          # ===== MEMORY =====
          - name: ciscoMemoryPoolUsed
            oid: 1.3.6.1.4.1.9.9.48.1.1.1.5
            type: gauge
            indexes:
              - labelname: pool
                type: gauge

          - name: ciscoMemoryPoolFree
            oid: 1.3.6.1.4.1.9.9.48.1.1.1.6
            type: gauge
            indexes:
              - labelname: pool
                type: gauge

          # ===== TEMPERATURE =====
          - name: ciscoEnvMonTemperatureStatusValue
            oid: 1.3.6.1.4.1.9.9.13.1.3.1.3
            type: gauge
            indexes:
              - labelname: sensor
                type: gauge

          # ===== PSU =====
          - name: ciscoEnvMonSupplyState
            oid: 1.3.6.1.4.1.9.9.13.1.5.1.3
            type: gauge
            indexes:
              - labelname: supply
                type: gauge

          # ===== FAN =====
          - name: ciscoEnvMonFanState
            oid: 1.3.6.1.4.1.9.9.13.1.4.1.3
            type: gauge
            indexes:
              - labelname: fan
                type: gauge

          # ===== INTERFACE TRAFFIC =====
          - name: ifHCInOctets
            oid: 1.3.6.1.2.1.31.1.1.1.6
            type: counter
            indexes:
              - labelname: ifIndex
                type: gauge

          - name: ifHCOutOctets
            oid: 1.3.6.1.2.1.31.1.1.1.10
            type: counter
            indexes:
              - labelname: ifIndex
                type: gauge

          # ===== INTERFACE ERRORS =====
          - name: ifInErrors
            oid: 1.3.6.1.2.1.2.2.1.14
            type: counter
            indexes:
              - labelname: ifIndex
                type: gauge

          - name: ifOutErrors
            oid: 1.3.6.1.2.1.2.2.1.20
            type: counter
            indexes:
              - labelname: ifIndex
                type: gauge

          # ===== PORT STATUS =====
          - name: ifOperStatus
            oid: 1.3.6.1.2.1.2.2.1.8
            type: gauge
            indexes:
              - labelname: ifIndex
                type: gauge
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"snmp.yml":"auths:\n  cisco_v2:\n    version: 2\n    community: ICCBS-RO\n\nmodules:\n  cisco:\n\n    walk:\n      - 1.3.6.1.2.1.1\n      - 1.3.6.1.2.1.2.2\n      - 1.3.6.1.2.1.31.1.1\n      - 1.3.6.1.4.1.9.9.109.1.1.1.1\n      - 1.3.6.1.4.1.9.9.48.1.1.1\n      - 1.3.6.1.4.1.9.9.13.1\n\n    lookups:\n      - source_indexes: [ifIndex]\n        lookup: ifName\n\n      - source_indexes: [ifIndex]\n        lookup: ifAlias\n\n      - source_indexes: [ifIndex]\n        lookup: ifDescr\n\n    metrics:\n\n      # ===== UPTIME =====\n      - name: sysUpTime\n        oid: 1.3.6.1.2.1.1.3.0\n        type: gauge\n\n      # ===== CPU =====\n      - name: cpmCPUTotal5minRev\n        oid: 1.3.6.1.4.1.9.9.109.1.1.1.1.8\n        type: gauge\n        indexes:\n          - labelname: cpu\n            type: gauge\n\n      # ===== MEMORY =====\n      - name: ciscoMemoryPoolUsed\n        oid: 1.3.6.1.4.1.9.9.48.1.1.1.5\n        type: gauge\n        indexes:\n          - labelname: pool\n            type: gauge\n\n      - name: ciscoMemoryPoolFree\n        oid: 1.3.6.1.4.1.9.9.48.1.1.1.6\n        type: gauge\n        indexes:\n          - labelname: pool\n            type: gauge\n\n      # ===== TEMPERATURE =====\n      - name: ciscoEnvMonTemperatureStatusValue\n        oid: 1.3.6.1.4.1.9.9.13.1.3.1.3\n        type: gauge\n        indexes:\n          - labelname: sensor\n            type: gauge\n\n      # ===== PSU =====\n      - name: ciscoEnvMonSupplyState\n        oid: 1.3.6.1.4.1.9.9.13.1.5.1.3\n        type: gauge\n        indexes:\n          - labelname: supply\n            type: gauge\n\n      # ===== FAN =====\n      - name: ciscoEnvMonFanState\n        oid: 1.3.6.1.4.1.9.9.13.1.4.1.3\n        type: gauge\n        indexes:\n          - labelname: fan\n            type: gauge\n\n      # ===== INTERFACE TRAFFIC =====\n      - name: ifHCInOctets\n        oid: 1.3.6.1.2.1.31.1.1.1.6\n        type: counter\n        indexes:\n          - labelname: ifIndex\n            type: gauge\n\n      - name: ifHCOutOctets\n        oid: 1.3.6.1.2.1.31.1.1.1.10\n        type: counter\n        indexes:\n          - labelname: ifIndex\n            type: gauge\n\n      # ===== INTERFACE ERRORS =====\n      - name: ifInErrors\n        oid: 1.3.6.1.2.1.2.2.1.14\n        type: counter\n        indexes:\n          - labelname: ifIndex\n            type: gauge\n\n      - name: ifOutErrors\n        oid: 1.3.6.1.2.1.2.2.1.20\n        type: counter\n        indexes:\n          - labelname: ifIndex\n            type: gauge\n\n      # ===== PORT STATUS =====\n      - name: ifOperStatus\n        oid: 1.3.6.1.2.1.2.2.1.8\n        type: gauge\n        indexes:\n          - labelname: ifIndex\n            type: gauge\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"snmp-exporter-config","namespace":"monitoring"}}
  creationTimestamp: "2026-02-04T17:56:08Z"
  name: snmp-exporter-config
  namespace: monitoring
  resourceVersion: "33698927"
  uid: 731430a6-1439-45ea-a32c-4d7c1c65478c
