version: "3.8"

services:
  django:
      build: .
      container_name: django
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
         - .:/app
      ports:
         - "8000:8000"
      depends_on:
         - DBiccbs

  DBiccbs:
      image: postgres
      container_name: DBiccbs
      environment:
         - POSTGRES_DB=postgres
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=postgres
         - POSTGRES_HOST=postgres
      ports:
         - "5432:5432"

   
