apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepseek-coder
  namespace: ai-models
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deepseek-coder
  template:
    metadata:
      labels:
        app: deepseek-coder
    spec:
      nodeSelector:
        kubernetes.io/hostname: ai-38
      containers:
      - name: deepseek
        image: vllm/vllm-openai:v0.8.5
        imagePullPolicy: IfNotPresent
        args:
          - "--model"
          - "deepseek-ai/deepseek-coder-6.7b-instruct"
          - "--gpu-memory-utilization"
          - "0.90"
          - "--max-model-len"
          - "1024"
          - "--enforce-eager"
          - "--dtype"
          - "float16"


        ports:
        - containerPort: 8000
        volumeMounts:
        - mountPath: /root/.cache/huggingface
          name: model-cache
        resources:
          limits:
            nvidia.com/gpu: 1
      #volumes:
      #- name: model-cache
        #persistentVolumeClaim:
          #claimName: hf-model-cache

      volumes:
      - name: model-cache
        hostPath:
          path: /data/hf-cache
          type: DirectoryOrCreate
