apiVersion: v1
kind: PersistentVolume
metadata:
  name: hf-model-cache-pv
spec:
  capacity:
    storage: 500Gi # Or whatever size you need
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-shared
  nfs:
    server: 172.16.2.40
    path: /mnt/shared-data/hf_cache # Give it its own subfolder
