apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hf-model-cache
  namespace: ai-models
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-shared
  volumeName: nfs-shared-data-pv # THIS LINKS IT TO THE 3Ti VOLUME
  resources:
    requests:
      storage: 200Gi
